name: Deploy to IIS

on:
  workflow_dispatch:

jobs:
  deploy:

    runs-on: self-hosted

    steps:

    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: website
        path: deploy

    - name: Stop IIS Site
      shell: powershell
      run: |
        Stop-WebSite -Name "Registar Form"

    - name: Copy Files
      shell: powershell
      run: |
        Copy-Item "deploy\*" `
        "C:\inetpub\wwwroot\wss\VirtualDirectories\Registar Form" `
        -Recurse -Force

    - name: Start IIS Site
      shell: powershell
      run: |
        Start-WebSite -Name "Registar Form"
