deploy:
  runs-on: self-hosted

  steps:

  - uses: actions/checkout@v4

  - name: Publish
    run: dotnet publish -c Release -o publish

  - name: Stop IIS Site
    run: |
      powershell Stop-WebSite -Name "Registar Form"

  - name: Copy Files
    run: |
      xcopy publish C:\inetpub\wwwroot\wss\VirtualDirectories\Registar Form /E /Y

  - name: Start IIS Site
    run: |
      powershell Start-WebSite -Name "Registar Form"