name: CD
on:
  workflow_run:
    workflows:
      - .NET
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: website
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path: publish          
      - name: Verify Download
        run: |
          ls -R publish          
      - name: Copy Files
        run: |
            mkdir -p /tmp/Deepthi/Deploy
              cp -r publish/. /tmp/Deepthi/Deploy/
      - name: Verify Deploy Folder
        run: |
          ls -R /tmp/Deepthi/Deploy


     
